apiVersion: kafka-connect.b1zzu.net/v1alpha1
kind: Connector
metadata:
  labels:
    app.kubernetes.io/name: kafka-connect-operator
    app.kubernetes.io/managed-by: kustomize
  # annotations:
  #   # Control connector state: running (default), paused, or stopped
  #   kafka-connect.b1zzu.net/state: running
  name: my-connector
spec:
  cluster:
    name: my-cluster
  config:
    connector.class: org.apache.kafka.connect.file.FileStreamSourceConnector
    tasks.max: "1"
    file: /dev/null
    topic: connect-file-test
